### ISSUE TITLE
Recording Mode Update Required

### ISSUE THREAD

**Issue by rehpa** [tomwpublic/hubitat_unifiProtect#10]
I have a new Hubitat setup and I've been testing this driver you have here.  Enjoying it so far, but I found one issue I wanted to share.  With my setup I have to change one of the Recording Mode values in the unifiProtectCamera driver for it to work correctly.  Without this change you are unable to set the mode back to "detections".

The word "motion" in this function does not work in my setup, it must be changed to "detections".  Maybe you could just add that value to the array if "motion" is still valid in other use cases.

`def setRecordingMode(mode)
{
    if(!(["always", "motion", "never"].contains(mode)))
    {
        log.debug "unsupported recording mode (${mode})"
        return
    }
    
    try
    {
        getParent()?.httpExecWithAuthCheck("PATCH", parent?.genParamsMain(getCameraBaseUrl(), new groovy.json.JsonOutput().toJson([recordingSettings: [mode: mode]])), true)
    }
    catch (Exception e)
    {
        log.debug "setRecordingMode() failed: ${e.message}"
    }
}`

My current setup where this change is required
CloudKey Gen2
Unifi OS: 2.4.10
Network: 7.1.66
Protect: 2.0.1

Thank you for taking the time to build and share this driver with the community!

**Comment by tomwpublic** [comment]
Good catch -- I made a change to add "detections" and also left "motion" as supported, since that name worked on older versions.

https://github.com/tomwpublic/hubitat_unifiProtect/commit/2e37b25a058cf6c69f1baebc034655edf3d19c38
