### ISSUE TITLE
isDark attribute true/false values not showing in Rule Machine

### ISSUE THREAD

**Issue by echao2012** [tomwpublic/hubitat_unifiProtect#12]
If I try to make a conditional statement in Hubitat's Rule Machine, selecting Custom Attribute, and using the isDark attribute, the true/false values are not shown in the dropdown menu.

It looks like quotes are missing around the enum values, so for the doorbell, camera, and light change:
`attribute "isDark", "enum", [true, false]`
to
`attribute "isDark", "enum", ["true", "false"]`

**Comment by tomwpublic** [comment]
https://github.com/tomwpublic/hubitat_unifiProtect/commit/e66b3def5a65c3910656d4d3f168dcc95880313a

Fixed here.  Thanks for reporting it.  If you used HPM to install, just use "Repair", because I didn't bump the version for this fix.
