### ISSUE TITLE
Support for Motion Zones

### ISSUE THREAD

**Issue by divbell** [tomwpublic/hubitat_unifiProtect#6]
Camera motion is working fantastically but I wonder if there is a way to ingest the defined motion zones for a camera.  It's retrieving the details for it, I can see, but doesn't create child devices that can be incorporated into basic rules.

If this isn't currently supported, I think it would be a really useful feature in the future.

**Comment by tomwpublic** [comment]
I really like this idea, but after some research and experimentation I found that the info on specific zones for motion events does not seem to be reported by the UniFi APIs.

The main project which I based on this on indicates that it may be a possible future enhancement:  https://github.com/hjdhjd/homebridge-unifi-protect/issues/251

I'll monitor for any additions to the UniFi APIs that would enable this.  In the meantime, please let me know if you can find a place in the web interface for UniFi Protect that reports the motion zone for a motion Event.
